project:
  type: website

bibliography: references.bib
toc: true

website:
  title: deep_tensor
  navbar:
    pinned: true
    search: true
    left:
      - text: "Home"
        href: index.qmd  
      - text: "Examples"
        href: examples/index.qmd
      - text: "API Reference"
        href: reference/index.qmd
      - text: "Theory"
        href: theory.qmd
    right:
      - icon: github
        href: https://github.com/DeepTransport/deep-tensor-py
    
  sidebar: 
    - id: examples
      title: Examples
      style: floating
      align: left
      collapse-level: 2
      contents:
        - title: Examples
          href: examples/index.qmd
        - section: Bayesian Inference
          contents:
          - title: SIR Model
            href: examples/sir/example_inference.ipynb
          - title: Shock Absorber Model
            href: examples/shock/example_inference.ipynb
          - title: Logistic Regression
            href: examples/logistic/example_inference.ipynb
          - title: Heat Equation
            href: examples/heat/example_inference.ipynb
        - section: Rare Event Estimation
          contents:
          - title: SIR Model
            href: examples/sir/example_rare_event.ipynb

execute:
  freeze: auto

format:
  html:
    theme:
      light: [flatly, styles.css, styles-light.css]
      dark: [darkly, styles.css, styles-dark.css]

metadata-files:
  - _sidebar.yml

interlinks:
  sources:
    torch:
      url: https://pytorch.org/docs/stable/
    python:
      url: https://docs.python.org/3/

quartodoc:

  style: pkgdown
  title: API Reference
  package: deep_tensor
  version: "1.0.0"
  render_interlinks: false
  
  renderer:
    style: markdown
    table_style: description-list
    show_signature_annotations: true
    display_name: relative

  sidebar: _sidebar.yml

  sections:

    - title: Deep Inverse Rosenblatt Transport
      desc: An object used to generate an approximate coupling between random variables using a composition of squared inverse Rosenblatt transports, constructed using functional tensor trains.
      contents:
        - name: DIRT
          members: [eval_potential, eval_potential_cond, eval_rt, eval_irt, eval_cirt, eval_irt_pullback, eval_cirt_pullback, random, sobol]
        - name: DIRTOptions

    - title: Target Functions
      desc: Functions to approximate.
      contents: 
        - name: TargetFunc
          members: []
        - name: RareEventFunc
          members: []

    - title: Preconditioners
      desc: Initial guesses for the mapping between the reference random variable and the target random variable.
      contents:
        - name: Preconditioner
          members: [Q, Q_inv, neglogdet_Q, neglogdet_Q_inv]
        - name: IdentityMapping
          members: []
        - name: UniformMapping
          members: []
        - name: GaussianMapping
          members: []

    - title: Reference Densities
      desc: Product-form reference densities used as part of DIRT construction.
      contents:
        - name: GaussianReference
          members: [random, sobol]
        - name: UniformReference
          members: [random, sobol]

    - title: Domain Mappings
      desc: Mappings between the approximation domain and the basis functions used as part of the functional tensor trains.
      contents:
        - name: BoundedDomain
          members: []

    - title: Functional Tensor Trains
      desc: Objects used to construct functional tensor train approximations.
      contents:
        - name: FTT
          members: [approximate, eval]
        - name: EFTT
          members: [approximate, eval]
        - name: ApproxBases
          members: []
        - name: TT
          members: [initialise, sweep, round]
        - name: TTOptions
          members: []

    - title: Basis Functions
      desc: Basis functions used for functional tensor train approximations.
      contents:
        - name: Lagrange1
          members: []
        - name: LagrangeP
          members: []
        - name: Chebyshev1st
          members: []
        - name: Chebyshev2nd
          members: []
        - name: Fourier
          members: []
        - name: Legendre
          members: []

    - title: Bridges
      desc: Objects used to generate the intermediate densities approximated during DIRT construction.
      contents:
        - name: SingleLayer
          members: []
        - name: Tempering
          members: []
        - name: SigmoidSmoothing
          members: []

    - title: Debiasing
      desc: Functions used to remove the bias associated with the use of an approximation to the target density function.
      contents:
        - name: run_importance_sampling 
        - name: run_independence_sampler
        - name: run_irt_pcn
        - name: run_cirt_pcn
        - name: ImportanceSamplingResult
        - name: MCMCResult