project:
  type: website

website:
  title: deep_tensor
  navbar:
    pinned: true
    search: true
    left:
      - text: "Home"
        href: index.qmd  
      - text: "API Reference"
        href: reference/index.qmd
    right:
      - icon: github
        href: https://github.com/DeepTransport/deep-tensor-py

execute:
  freeze: auto

format:
  html:
    theme:
      dark: [darkly, styles.css, styles-dark.css]
      light: [flatly, styles.css, styles-light.css]

metadata-files:
  - _sidebar.yml

interlinks:
  sources:
    torch:
      url: https://pytorch.org/docs/stable/
    python:
      url: https://docs.python.org/3/
    # quartodoc-test:
    #   url: https://machow.github.io/quartodoc
    #   inv: objects-test.txt

quartodoc:

  style: pkgdown
  title: API Reference
  package: deep_tensor
  version: "1.0.0"
  render_interlinks: true
  
  renderer:
    style: markdown
    table_style: description-list
    show_signature_annotations: true
    display_name: relative

  sidebar: _sidebar.yml

  sections:

    - title: Deep Inverse Rosenblatt Transport
      desc: An object used to generate an approximate coupling between random variables using a composition of squared inverse Rosenblatt transports, constructed using functional tensor trains.
      package: deep_tensor
      contents:
        - name: TTDIRT
          members: [eval_potential, eval_pdf, eval_rt, eval_irt, random, sobol]

    - title: Prior Transformation
      desc: An object which defines a mapping between the prior and a reference density.
      contents:
        - name: PriorTransformation
          members: []

    - title: Polynomial Bases
      desc: Polynomial bases used to construct a functional tensor train.
      package: deep_tensor
      contents:
        - name: Lagrange1
          members: []
        - name: LagrangeP
          members: []
        - name: Chebyshev1st
          members: []
        - name: Chebyshev2nd
          members: []
        - name: Fourier
          members: []
        - name: Legendre
          members: []

    - title: Domain Mappings
      desc: Mappings between the approximation domain and the domain of the polynomial basis.
      package: deep_tensor
      contents:
        - name: BoundedDomain
          members: []
        - name: AlgebraicMapping
          members: []
        - name: LogarithmicMapping
          members: []
    
    - title: Options
      desc: Options for configuring the FTT and DIRT construction.
      package: deep_tensor
      contents:
        - name: TTOptions
        - name: DIRTOptions

    - title: Reference Densities
      desc: Product-form reference densities used as part of DIRT construction.
      package: deep_tensor
      contents:
        - name: GaussianReference
          members: [random, sobol]
        - name: UniformReference
          members: [random, sobol]

    - title: Bridges
      desc: Objects used to generate the intermediate densities approximated during DIRT construction.
      package: deep_tensor
      contents:
        - name: Tempering1
          members: []