project:
  type: website

website:
  title: deep_tensor
  navbar:
    pinned: true
    search: true
    left:
      - text: "Home"
        href: index.qmd  
      - text: "Examples"
        href: examples/index.qmd
      - text: "API Reference"
        href: reference/index.qmd
    right:
      - icon: github
        href: https://github.com/DeepTransport/deep-tensor-py
    
  sidebar: 
    - id: examples
      title: Examples
      style: floating
      align: left
      collapse-level: 1
      contents:
        - title: Examples
          href: examples/index.qmd
        - title: SIR Model
          href: examples/sir.qmd


execute:
  freeze: auto

format:
  html:
    theme:
      light: [flatly, styles.css, styles-light.css]
      dark: [darkly, styles.css, styles-dark.css]

metadata-files:
  - _sidebar.yml

interlinks:
  sources:
    torch:
      url: https://pytorch.org/docs/stable/
    python:
      url: https://docs.python.org/3/

quartodoc:

  style: pkgdown
  title: API Reference
  package: deep_tensor
  version: "1.0.0"
  render_interlinks: true
  
  renderer:
    style: markdown
    table_style: description-list
    show_signature_annotations: true
    display_name: relative

  sidebar: _sidebar.yml

  sections:

    - title: Deep Inverse Rosenblatt Transport
      desc: An object used to generate an approximate coupling between random variables using a composition of squared inverse Rosenblatt transports, constructed using functional tensor trains.
      package: deep_tensor
      contents:
        - name: DIRT
          members: [eval_potential, eval_pdf, eval_rt, eval_irt, eval_cirt, eval_irt_pullback, random, sobol]

    - title: Preconditioners
      desc: Initial guesses for the mapping between the reference random variable and the target random variable.
      contents:
        - name: Preconditioner
          members: []
        - name: IdentityMapping
          members: []
        - name: UniformMapping
          members: []

    - title: Polynomial Bases
      desc: Polynomial bases used to construct a functional tensor train.
      package: deep_tensor
      contents:
        - name: Lagrange1
          members: []
        - name: LagrangeP
          members: []
        - name: Chebyshev1st
          members: []
        - name: Chebyshev2nd
          members: []
        - name: Fourier
          members: []
        - name: Legendre
          members: []

    - title: Domain Mappings
      desc: Mappings between the approximation domain and the domain of the polynomial basis.
      package: deep_tensor
      contents:
        - name: BoundedDomain
          members: []
    
    - title: Options
      desc: Options for configuring the FTT and DIRT construction.
      package: deep_tensor
      contents:
        - name: TTOptions
        - name: DIRTOptions

    - title: Reference Densities
      desc: Product-form reference densities used as part of DIRT construction.
      package: deep_tensor
      contents:
        - name: GaussianReference
          members: [random, sobol]
        - name: UniformReference
          members: [random, sobol]

    - title: Bridges
      desc: Objects used to generate the intermediate densities approximated during DIRT construction.
      package: deep_tensor
      contents:
        - name: SingleLayer
          members: []
        - name: Tempering
          members: []

    - title: Debiasing
      desc: Functions used to remove the bias associated with the use of an approximation to the target density function.
      package: deep_tensor
      contents:
        - name: run_importance_sampling 
        - name: run_independence_sampler
        - name: run_dirt_pcn
        - name: ImportanceSamplingResult
        - name: MCMCResult