---
format: html
bibliography: "references.bib"
execute: 
  eval: false
---

The $\texttt{deep\_tensor}$ package contains a [PyTorch](https://pytorch.org) implementation of the deep inverse Rosenblatt transport (DIRT) algorithm introduced by @Cui2022.

# Installation

$\texttt{deep\_tensor}$ can be installed using pip:

```{python}

pip install deep-tensor-py

```

The package can then be imported using

```{python}

import deep_tensor as dt

```

# Getting Started

Check out the [examples page](/examples/index.qmd) and [API reference](/reference/index.qmd) for help getting started with $\texttt{deep\_tensor}$.

# Further Reading

The deep inverse Rosenblatt transport (DIRT) algorithm [@Cui2022] uses a composition of mappings, constructed using functional tensor trains, to approximate the Rosenblatt transport between an arbitrary target density function and a simple product-form reference density. Early work on functional tensor train (FTT) approximations to probability density functions was conducted by @Dolgov2020. @Cui2022 introduced the idea of using a composition of FTT-based mappings to provide a more accurate characterisation of highly correlated or concentrated probability densities.

The DIRT methodology has also been used for problems including amortised inference [@Cui2023], rare event estimation [@Cui2024], sequential inference [@Zhao2024], and optimal experimental design [@Koval2024].