# EFTT { #deep_tensor.EFTT }

```python
EFTT(
    self,
    bases: ApproxBases,
    tt: TT,
    num_error_samples: int = 1000,
    num_pod_samples: int = 30,
    tol_pod: float = 1e-12,
)
```

An extended functional tensor train, defined on $[-1, 1]^{d}$.

## Parameters {.doc-section .doc-section-parameters}

<code>[**bases**]{.parameter-name} [:]{.parameter-annotation-sep} [ApproxBases]{.parameter-annotation}</code>

:   A set of basis functions for each dimension of the FTT.

<code>[**tt**]{.parameter-name} [:]{.parameter-annotation-sep} [TT]{.parameter-annotation}</code>

:   A tensor train object.

<code>[**num_error_samples**]{.parameter-name} [:]{.parameter-annotation-sep} [int]{.parameter-annotation} [ = ]{.parameter-default-sep} [1000]{.parameter-default}</code>

:   The number of samples to use to estimate the $L_{2}$ error of  the FTT during its construction.

<code>[**num_pod_samples**]{.parameter-name} [:]{.parameter-annotation-sep} [int]{.parameter-annotation} [ = ]{.parameter-default-sep} [30]{.parameter-default}</code>

:   The number of samples to use when generating a fibre matrices  used to compute the reduced bases in each coordinate.

<code>[**tol_pod**]{.parameter-name} [:]{.parameter-annotation-sep} [float]{.parameter-annotation} [ = ]{.parameter-default-sep} [1e-12]{.parameter-default}</code>

:   The tolerance to use when truncating singular values when  applying the POD to obtain the reduced bases in each  coordinate.

## Methods

| Name | Description |
| --- | --- |
| [approximate](#deep_tensor.EFTT.approximate) | Constructs a FTT approximation to a target function. |
| [eval](#deep_tensor.EFTT.eval) | Evaluates the FTT. |

### approximate { #deep_tensor.EFTT.approximate }

```python
EFTT.approximate(
    target_func: Callable[[Tensor], Tensor],
    reference: Reference | None = None,
)
```

Constructs a FTT approximation to a target function.

#### Parameters {.doc-section .doc-section-parameters}

<code>[**target_func**]{.parameter-name} [:]{.parameter-annotation-sep} [Callable\[\[Tensor\], Tensor\]]{.parameter-annotation}</code>

:   The target function, $f : [-1, 1]^{d} \rightarrow \mathbb{R}$.

<code>[**reference**]{.parameter-name} [:]{.parameter-annotation-sep} [Reference \| None]{.parameter-annotation} [ = ]{.parameter-default-sep} [None]{.parameter-default}</code>

:   The reference measure. If provided, this will be used to  generate the samples to build the fibre matrices and  generate the initial index sets for the underlying TT.  Otherwise, the samples will be drawn uniformly.

### eval { #deep_tensor.EFTT.eval }

```python
EFTT.eval(ls: Tensor, direction: Direction | None = None)
```

Evaluates the FTT.

Returns the functional tensor train approximation to the target 
function for either the first or last $k$ variables, for a set 
of points mapped to the domain of the basis functions.

#### Parameters {.doc-section .doc-section-parameters}

<code>[**ls**]{.parameter-name} [:]{.parameter-annotation-sep} [Tensor]{.parameter-annotation}</code>

:   An $n \times d$ matrix containing a set of samples mapped  to the domain of the FTT basis functions.

<code>[**direction**]{.parameter-name} [:]{.parameter-annotation-sep} [Direction \| None]{.parameter-annotation} [ = ]{.parameter-default-sep} [None]{.parameter-default}</code>

:   The direction in which to iterate over the cores.

#### Returns {.doc-section .doc-section-returns}

<code>[**Gs_prod**]{.parameter-name} [:]{.parameter-annotation-sep} [Tensor]{.parameter-annotation}</code>

:   An $n \times n_{k}$ matrix, where each row contains the  product of the first or last (depending on direction) $k$  tensor cores evaluated at the corresponding sample in `ls`.