# API Reference {.doc .doc-index}

## Deep Inverse Rosenblatt Transport

An object used to generate an approximate coupling between random variables using a composition of squared inverse Rosenblatt transports, constructed using functional tensor trains.

| | |
| --- | --- |
| [DIRT](DIRT.qmd#deep_tensor.DIRT) | Deep (squared) inverse Rosenblatt transport. |
| [DIRTOptions](DIRTOptions.qmd#deep_tensor.DIRTOptions) | Options for configuring the construction of a DIRT object. |

## Target Functions

Functions to approximate.

| | |
| --- | --- |
| [TargetFunc](TargetFunc.qmd#deep_tensor.TargetFunc) | The negative logarithm of a density function to be approximated. |
| [RareEventFunc](RareEventFunc.qmd#deep_tensor.RareEventFunc) | A function for rare event estimation problems. |

## Preconditioners

Initial guesses for the mapping between the reference random variable and the target random variable.

| | |
| --- | --- |
| [Preconditioner](Preconditioner.qmd#deep_tensor.Preconditioner) | The base class for preconditioning mappings. |
| [IdentityMapping](IdentityMapping.qmd#deep_tensor.IdentityMapping) | An identity mapping. |
| [UniformMapping](UniformMapping.qmd#deep_tensor.UniformMapping) | A mapping between the reference density and a uniform density. |
| [GaussianMapping](GaussianMapping.qmd#deep_tensor.GaussianMapping) | A mapping between two Gaussian densities. |

## Reference Densities

Product-form reference densities used as part of DIRT construction.

| | |
| --- | --- |
| [GaussianReference](GaussianReference.qmd#deep_tensor.GaussianReference) | The standard $d$-dimensional Gaussian density, $\mathcal{N}(\boldsymbol{0}_{d}, \boldsymbol{I}_{d})$. |
| [UniformReference](UniformReference.qmd#deep_tensor.UniformReference) | The standard $d$-dimensional uniform density, $\mathcal{U}([0, 1]^{d})$. |

## Domain Mappings

Mappings between the approximation domain and the basis functions used as part of the functional tensor trains.

| | |
| --- | --- |
| [BoundedDomain](BoundedDomain.qmd#deep_tensor.BoundedDomain) | Mapping from a bounded domain to $[-1, 1]$. |

## Functional Tensor Trains

Objects used to construct functional tensor train approximations.

| | |
| --- | --- |
| [FTT](FTT.qmd#deep_tensor.FTT) | A functional tensor train, defined on $[-1, 1]^{d}$. |
| [EFTT](EFTT.qmd#deep_tensor.EFTT) | An extended functional tensor train, defined on $[-1, 1]^{d}$. |
| [EFTTOptions](EFTTOptions.qmd#deep_tensor.EFTTOptions) | Options for configuring the construction of an EFTT object. |
| [TT](TT.qmd#deep_tensor.TT) | A tensor train factorisation. |
| [TTOptions](TTOptions.qmd#deep_tensor.TTOptions) | Options for configuring the construction of a TT object. |

## Basis Functions

Basis functions used for functional tensor train approximations.

| | |
| --- | --- |
| [Lagrange1](Lagrange1.qmd#deep_tensor.Lagrange1) | Piecewise linear polynomials. |
| [LagrangeP](LagrangeP.qmd#deep_tensor.LagrangeP) | Higher-order piecewise Lagrange polynomials. |
| [Chebyshev1st](Chebyshev1st.qmd#deep_tensor.Chebyshev1st) | Chebyshev polynomials of the first kind. |
| [Chebyshev2nd](Chebyshev2nd.qmd#deep_tensor.Chebyshev2nd) | Chebyshev polynomials of the second kind. |
| [Fourier](Fourier.qmd#deep_tensor.Fourier) | Fourier polynomials. |
| [Legendre](Legendre.qmd#deep_tensor.Legendre) | Legendre polynomials. |

## Bridges

Objects used to generate the intermediate densities approximated during DIRT construction.

| | |
| --- | --- |
| [SingleLayer](SingleLayer.qmd#deep_tensor.SingleLayer) | Constructs the DIRT using a single layer. |
| [Tempering](Tempering.qmd#deep_tensor.Tempering) | Likelihood tempering. |
| [SigmoidSmoothing](SigmoidSmoothing.qmd#deep_tensor.SigmoidSmoothing) | Uses a sigmoid function in place of an indicator function. |
| [GaussianSmoothing](GaussianSmoothing.qmd#deep_tensor.GaussianSmoothing) | Uses a Gaussian CDF in place of an indicator function. |

## Subspaces

Objects used to construct DIRT objects in reduced spaces.

| | |
| --- | --- |
| [IdentitySubspace](IdentitySubspace.qmd#deep_tensor.IdentitySubspace) | Identity subspace (*i.e.,* no dimension reduction). |
| [LikelihoodInformedSubspace](LikelihoodInformedSubspace.qmd#deep_tensor.LikelihoodInformedSubspace) | A likelihood-informed subspace. |

## Debiasing

Functions used to remove the bias associated with the use of an approximation to the target density function.

| | |
| --- | --- |
| [run_importance_sampling](run_importance_sampling.qmd#deep_tensor.run_importance_sampling) | Computes the importance weights associated with a set of samples. |
| [run_independence_sampler](run_independence_sampler.qmd#deep_tensor.run_independence_sampler) | Runs an independence Metropolis-Hastings sampler. |
| [ImportanceSamplingResult](ImportanceSamplingResult.qmd#deep_tensor.ImportanceSamplingResult) | An object containing the results of importance sampling. |
| [MCMCResult](MCMCResult.qmd#deep_tensor.MCMCResult) | An object containing a constructed Markov chain. |