# TT { #deep_tensor.TT }

```python
TT(options: TTOptions | None = None, device: torch.device = torch.device('cpu'))
```

A tensor train factorisation.

This class computes and stores a tensor train factorisation of the 
discretisation of an arbitrary function on a tensor-product grid, 
using the alternating cross approximation algorithm outlined in 
@Oseledets2010. 

## Parameters {.doc-section .doc-section-parameters}

<code>[**options**]{.parameter-name} [:]{.parameter-annotation-sep} [TTOptions \| None]{.parameter-annotation} [ = ]{.parameter-default-sep} [None]{.parameter-default}</code>

:   Parameters which control the construction of the tensor train  factorisation.

## Methods

| Name | Description |
| --- | --- |
| [initialise](#deep_tensor.TT.initialise) | Initialises the TT. |
| [sweep](#deep_tensor.TT.sweep) | Runs a single cross iteration. |
| [round](#deep_tensor.TT.round) | Rounds the TT cores.  |

### initialise { #deep_tensor.TT.initialise }

```python
TT.initialise(target_func: Callable[[Tensor], Tensor], grid: Grid)
```

Initialises the TT.

#### Parameters {.doc-section .doc-section-parameters}

<code>[**target_func**]{.parameter-name} [:]{.parameter-annotation-sep} [Callable\[\[Tensor\], Tensor\]]{.parameter-annotation}</code>

:   A function that takes an $n \times d$ matrix with rows  containing samples from the tensor product grid, and  returns an $n$-dimensional vector containing the values of  the target function evaluated at each sample.

<code>[**grid**]{.parameter-name} [:]{.parameter-annotation-sep} [Grid]{.parameter-annotation}</code>

:   The tensor product grid used to construct the TT.

### sweep { #deep_tensor.TT.sweep }

```python
TT.sweep()
```

Runs a single cross iteration.

If cross iterations have been run previously, this performs a 
sweep over the cores in the opposite order to the previous 
sweep.

### round { #deep_tensor.TT.round }

```python
TT.round(tol: float | None = None, max_rank: int | None = None)
```

Rounds the TT cores. 

Applies double rounding to get back to the starting direction.

#### Parameters {.doc-section .doc-section-parameters}

<code>[**tol**]{.parameter-name} [:]{.parameter-annotation-sep} [float \| None]{.parameter-annotation} [ = ]{.parameter-default-sep} [None]{.parameter-default}</code>

:   The tolerance to use when applying truncated SVD to round  each core.